name: ml-econ
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - ipykernel
  - dask
  - pyarrow
  - pyspark
  - shap
  - imbalanced-learn
  - xgboost
  - lightgbm
  - pip:
      - catboost
# Notes:
# - For faster installs on some systems, you may comment out pyspark or lightgbm.
# - After creating the env, register the kernel:
#   python -m ipykernel install --user --name=ml-econ --display-name "Python (ml-econ)"